/// MCP tool 名稱的唯一型別來源，避免 router 接受散落的任意字串。
enum MCPToolName: String, CaseIterable, Sendable {
    case contractDescribe = "mangakitchen.contract.describe"
    case workspaceList = "mangakitchen.workspace.list"
    case workspaceOpen = "mangakitchen.workspace.open"
    case workspacePages = "mangakitchen.workspace.pages"
    case workspaceActivate = "mangakitchen.workspace.activate"
    case workspaceRescan = "mangakitchen.workspace.rescan"
    case workspaceSetOutput = "mangakitchen.workspace.set_output"
    case workspaceConfigure = "mangakitchen.workspace.configure"
    case glossaryList = "mangakitchen.glossary.list"
    case glossaryUpsert = "mangakitchen.glossary.upsert"
    case glossaryRemove = "mangakitchen.glossary.remove"
    case modelLoad = "mangakitchen.model.load"
    case pageInspect = "mangakitchen.page.inspect"
    case pageUpdate = "mangakitchen.page.update"
    case pagePrepareAgentTask = "mangakitchen.page.prepare_agent_task"
    case pageSubmitAgentResult = "mangakitchen.page.submit_agent_result"
    case pageRender = "mangakitchen.page.render"
    case pageColorize = "mangakitchen.page.colorize"
    case pagePrepareColorizationTask = "mangakitchen.page.prepare_colorization_task"
    case pageSubmitColorizationResult = "mangakitchen.page.submit_colorization_result"
    case pageRenderColorization = "mangakitchen.page.render_colorization"
    case pageResetColorization = "mangakitchen.page.reset_colorization"
    case regionBatchUpdate = "mangakitchen.region.batch_update"
    case regionReorder = "mangakitchen.region.reorder"
    case pageDetectMasks = "mangakitchen.page.detect_masks"
    case pageTranslate = "mangakitchen.page.translate"
    case pageCompose = "mangakitchen.page.compose"
    case pageRunFull = "mangakitchen.page.run_full"
    case pageSupplementRegions = "mangakitchen.page.supplement_regions"
    case regionCreate = "mangakitchen.region.create"
    case regionUpdate = "mangakitchen.region.update"
    case regionRemove = "mangakitchen.region.remove"
}
